'use client';
import { useState, useEffect, useRef, useMemo, type FormEvent } from 'react';
import { LayoutDashboard, Building2, CreditCard, Flag, ScanLine, Zap, HeartPulse, ScrollText, Store, Settings, ChevronDown, ChevronRight, Plus, Search, Bell, ArrowUpRight, ArrowRight, RefreshCw, Download, Share2, ShieldCheck, X, Check, CircleHelp, SlidersHorizontal, MoreHorizontal, ExternalLink, Users, Link2, Trash2, Pause, Clock3, CheckCircle2, AlertTriangle, Layers3, Activity, Menu } from 'lucide-react';
import { demoAssets, types, type Asset, type Entry } from '../lib/data';
const nav=[{name:'Tá»•ng quan',icon:LayoutDashboard},{name:'Business Manager',icon:Building2,type:'BM'},{name:'TÃ i khoáº£n quáº£ng cÃ¡o',icon:CreditCard,type:'TKQC'},{name:'Page',icon:Flag,type:'Page'},{name:'Dataset / Pixel',icon:ScanLine,type:'Dataset/Pixel'},{name:'Tá»± Ä‘á»™ng hÃ³a',icon:Zap},{name:'Health Check',icon:HeartPulse},{name:'Nháº­t kÃ½ hoáº¡t Ä‘á»™ng',icon:ScrollText},{name:'Marketplace',icon:Store}];
const iconMap={BM:Building2,TKQC:CreditCard,Page:Flag,'Dataset/Pixel':ScanLine};
const good=(s:string)=>['LIVE','Truy cáº­p Ä‘Æ°á»£c','HoÃ n táº¥t'].includes(s);
const date=(s?:string)=>s?new Date(s).toLocaleString('vi-VN',{hour:'2-digit',minute:'2-digit',day:'2-digit',month:'2-digit'}):'ChÆ°a kiá»ƒm tra';
function Badge({status}:{status:string}){return <span className={`badge ${good(status)?'green':status==='DIE'?'red':status.includes('Chá»')||status==='Háº¡n cháº¿'?'amber':'neutral'}`}><span className="dot"/>{status}</span>;}
export default function Workspace(){
 const [view,setView]=useState('Tá»•ng quan'),[tab,setTab]=useState('BM'),[assets,setAssets]=useState<Asset[]>([]),[jobs,setJobs]=useState<Entry[]>([]),[logs,setLogs]=useState<Entry[]>([]),[services,setServices]=useState<Entry[]>([]),[connected,setConnected]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[toast,setToast]=useState('');
 const [demo,setDemo]=useState(false),[query,setQuery]=useState(''),[status,setStatus]=useState('all'),[country,setCountry]=useState('all'),[verified,setVerified]=useState('all'),[tier,setTier]=useState('all'),[advanced,setAdvanced]=useState(false),[selected,setSelected]=useState<string[]>([]),[modal,setModal]=useState(''),[detail,setDetail]=useState<Asset|null>(null),[sidebar,setSidebar]=useState(false),[page,setPage]=useState(1);
 const [formType,setFormType]=useState('BM'),[quantity,setQuantity]=useState(1),[interval,setIntervalValue]=useState(30),[shareBm,setShareBm]=useState(''),[random,setRandom]=useState(false),[shareIds,setShareIds]=useState<string[]>([]),[operation,setOperation]=useState('member'),[formError,setFormError]=useState('');
 const dialogRef=useRef<HTMLDialogElement>(null);
 const display=demo?demoAssets:assets;const bms=display.filter(a=>a.type==='BM');const currentType=nav.find(n=>n.name===view)?.type||tab;
 const rows=useMemo(()=>display.filter(a=>(view==='Health Check'||a.type===currentType)&&`${a.name} ${a.id}`.toLowerCase().includes(query.toLowerCase())&&(status==='all'||a.status===status)&&(country==='all'||a.country===country)&&(tier==='all'||a.tier===tier)&&(verified==='all'||a.verified===(verified==='yes'))),[display,view,currentType,query,status,country,tier,verified]);
 const pageRows=rows.slice((page-1)*8,page*8), unhealthy=display.filter(a=>['DIE','Háº¡n cháº¿','KhÃ´ng xÃ¡c Ä‘á»‹nh','Cáº§n kiá»ƒm tra quyá»n'].includes(a.status));
 async function load(){setError('');try{const r=await fetch('/api/workspace');const d=await r.json() as {error:string;assets:Asset[];jobs:Entry[];logs:Entry[];services:Entry[];connected:boolean};if(!r.ok)throw new Error(d.error);setAssets(d.assets);setJobs(d.jobs);setLogs(d.logs);setServices(d.services);setConnected(d.connected);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),6000);return()=>clearTimeout(timer);},[toast]);
 useEffect(()=>{setPage(1);setSelected([]);},[view,tab,query,status,country,tier,verified,demo]);
 useEffect(()=>{if(modal){dialogRef.current?.showModal();}else dialogRef.current?.close();setFormError('');},[modal]);
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void}}).modelContext;if(!context)return;const controller=new AbortController();try{context.registerTool({name:'filter_meta_assets',description:'Lá»c tÃ i nguyÃªn trong báº£ng theo tÃªn hoáº·c ID.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{if(!input||typeof(input as {query:string}).query!=='string')throw new Error('query pháº£i lÃ  chuá»—i');const q=(input as {query:string}).query;setQuery(q);setView('Health Check');return {query:q};}},{signal:controller.signal});}catch{}return()=>controller.abort();},[]);
 function go(name:string){setView(name);setSidebar(false);setQuery('');setStatus('all');setCountry('all');setVerified('all');setTier('all');}
 function open(name:string){setModal(name);setQuantity(1);setIntervalValue(30);setFormType(currentType);setFormError('');if(name==='share'){setShareBm(bms[0]?.id||'');setShareIds([]);setRandom(false);}}
 async function act(action:string,data:Record<string,unknown>={}){if(demo&&action!=='seed'){setToast('Äang xem dá»¯ liá»‡u máº«u. Chuyá»ƒn sang workspace Ä‘á»ƒ lÆ°u thay Ä‘á»•i.');return false;}setBusy(true);try{const r=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...data})});const d=await r.json() as {error:string;message:string};if(!r.ok)throw new Error(d.error);await load();setToast(d.message);return true;}catch(e){setFormError((e as Error).message);setToast((e as Error).message);return false;}finally{setBusy(false);}}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setFormError('');const f=Object.fromEntries(new FormData(e.currentTarget));let ok=false;
 if(modal==='create')ok=await act('job',{job:{...f,type:formType,operation:'create',count:quantity,interval,assetIds:[],name:`Táº¡o ${quantity} ${formType} Â· ${f.name}`}});
 else if(modal==='asset'||modal==='edit')ok=await act('asset',{asset:{...f,id:modal==='edit'?detail?.id:undefined,type:formType}});
 else if(modal==='share'){const eligible=display.filter(a=>a.type==='TKQC'&&a.parent===shareBm&&good(a.status));let ids=shareIds;if(random){if(quantity>eligible.length){setFormError(`Chá»‰ cÃ³ ${eligible.length} TKQC Ä‘á»§ Ä‘iá»u kiá»‡n.`);return;}const pool=[...eligible];for(let i=pool.length-1;i>0;i--){const j=Math.floor(crypto.getRandomValues(new Uint32Array(1))[0]/4294967296*(i+1));[pool[i],pool[j]]=[pool[j],pool[i]];}ids=pool.slice(0,quantity).map(a=>a.id);}if(!ids.length){setFormError('Chá»n Ã­t nháº¥t má»™t tÃ i khoáº£n quáº£ng cÃ¡o.');return;}ok=await act('job',{job:{...f,operation:'share',name:`Chia sáº» ${ids.length} TKQC cho ${f.partner}`,count:ids.length,interval:30,assetIds:ids,parent:shareBm,random}});}
 else if(modal==='member')ok=await act('job',{job:{...f,operation,name:`${operation==='member'?'Má»i thÃ nh viÃªn':operation==='connect'?'Káº¿t ná»‘i tÃ i nguyÃªn':'Thay Ä‘á»•i quyá»n'} Â· ${f.parent}`,count:1,interval:30,assetIds:[String(f.parent)]}});
 else if(modal==='service')ok=await act('service',{service:f});
 if(ok)setModal('');}
 function exportData(){const headers=['TÃªn','ID','Loáº¡i','Tráº¡ng thÃ¡i','Quá»‘c gia (nhÃ£n)','PhÃ¢n loáº¡i (nhÃ£n)','Háº¡n má»©c','Nguá»“n'];const lines=[headers,...rows.map(a=>[a.name,a.id,a.type,a.status,a.country,a.tier,a.limit,a.source])].map(row=>row.map(v=>'"'+String(v).replaceAll('"','""').replace(/^[=+@-]/,"'$&")+'"').join(','));const url=URL.createObjectURL(new Blob(['\ufeff'+lines.join('\r\n')],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download='ads-workspace.csv';a.click();URL.revokeObjectURL(url);setToast(`ÄÃ£ xuáº¥t ${rows.length} tÃ i nguyÃªn`);}
 const empty=!display.length;const eligible=display.filter(a=>a.type==='TKQC'&&a.parent===shareBm&&good(a.status));
 return <div className="app-shell">
 <aside className={`sidebar ${sidebar?'show':''}`}><a className="brand" href="/" aria-label="Ads Workspace"><span className="brand-mark"><Layers3 size={23}/></span><span>ads<span className="brand-light">workspace</span><small>META RESOURCE PLATFORM</small></span></a>
 <button className="workspace-select" onClick={()=>go('CÃ i Ä‘áº·t')}><span className="workspace-avatar">N</span><span>Nguyá»…n Workspace<small>KhÃ´ng gian cÃ¡ nhÃ¢n</small></span><ChevronDown size={15}/></button>
 <div className="nav-label">KHÃ”NG GIAN LÃ€M VIá»†C</div><nav>{nav.slice(0,5).map(n=><button key={n.name} className={`nav-item ${view===n.name?'active':''}`} onClick={()=>go(n.name)}><n.icon size={19}/><span>{n.name}</span>{n.type&&display.length>0&&<small>{display.filter(a=>a.type===n.type).length}</small>}</button>)}</nav>
 <div className="nav-label">Váº¬N HÃ€NH</div><nav>{nav.slice(5).map(n=><button key={n.name} className={`nav-item ${view===n.name?'active':''}`} onClick={()=>go(n.name)}><n.icon size={19}/><span>{n.name}</span>{n.name==='Health Check'&&unhealthy.length>0&&<small className="warning-count">{unhealthy.length}</small>}</button>)}</nav>
 <div className="sidebar-bottom"><div className="connection-card"><span className="connection-icon"><Link2 size={18}/></span><strong>{connected?'Meta Ä‘Ã£ cáº¥u hÃ¬nh':'Káº¿t ná»‘i tÃ i khoáº£n Meta'}</strong><p>Äá»“ng bá»™ tÃ i nguyÃªn cá»§a báº¡n vá» má»™t nÆ¡i.</p><button onClick={()=>open('settings')}>{connected?'Quáº£n lÃ½ káº¿t ná»‘i':'Thiáº¿t láº­p káº¿t ná»‘i'}<ArrowUpRight size={16}/></button></div><button className={`nav-item ${view==='CÃ i Ä‘áº·t'?'active':''}`} onClick={()=>go('CÃ i Ä‘áº·t')}><Settings size={19}/>CÃ i Ä‘áº·t workspace</button><div className="profile"><span className="avatar">N</span><span>Nguyá»…n Workspace<small>Chá»§ sá»Ÿ há»¯u</small></span><button className="icon-button" onClick={()=>open('help')} aria-label="Trá»£ giÃºp"><CircleHelp size={19}/></button></div></div></aside>
 {sidebar&&<button className="sidebar-scrim" aria-label="ÄÃ³ng menu" onClick={()=>setSidebar(false)}/>}
 <div className="main-wrap"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" aria-label="Má»Ÿ menu" onClick={()=>setSidebar(true)}><Menu/></button><span>Workspace</span><ChevronRight size={14}/><strong>{view}</strong></div><div className="top-actions"><span className={`connection-status ${connected?'connected':''}`}><span className="dot"/>{connected?'ÄÃ£ cáº¥u hÃ¬nh Meta':'ChÆ°a káº¿t ná»‘i Meta'}</span><button className="icon-button notification" aria-label="Xem cáº£nh bÃ¡o" onClick={()=>go('Health Check')}><Bell size={19}/>{unhealthy.length>0&&<i/>}</button><span className="avatar small">N</span></div></header>
 <main><div className="page-heading"><div><div className="eyebrow">META ADS OPERATIONS</div><h1>{view==='Tá»•ng quan'?'Tá»•ng quan workspace':view}</h1><p>{view==='Tá»•ng quan'?'ToÃ n bá»™ tÃ i nguyÃªn, má»™t gÃ³c nhÃ¬n.':view==='Tá»± Ä‘á»™ng hÃ³a'?'Thiáº¿t láº­p workflow, sá»‘ lÆ°á»£ng vÃ  tá»‘c Ä‘á»™ xá»­ lÃ½.':view==='Health Check'?'Theo dÃµi tráº¡ng thÃ¡i vÃ  cÃ¡c tÃ i nguyÃªn cáº§n xá»­ lÃ½.':view==='Marketplace'?'Danh má»¥c dá»‹ch vá»¥ vÃ  nhÃ  cung cáº¥p cá»§a workspace.':view==='Nháº­t kÃ½ hoáº¡t Ä‘á»™ng'?'Má»i thao tÃ¡c Ä‘á»u Ä‘Æ°á»£c lÆ°u láº¡i Ä‘á»ƒ theo dÃµi.':view==='CÃ i Ä‘áº·t'?'Quáº£n lÃ½ káº¿t ná»‘i vÃ  nguá»“n dá»¯ liá»‡u.':'Quáº£n lÃ½ tÃ i nguyÃªn vÃ  quyá»n truy cáº­p táº­p trung.'}</p></div><div className="heading-actions"><button className="button" disabled={busy} onClick={()=>connected?void act('sync'):open('settings')}><RefreshCw size={16} className={busy?'spin':''}/>Äá»“ng bá»™ Meta</button><button className="button primary" onClick={()=>open(view==='Marketplace'?'service':'create')}><Plus size={18}/>{view==='Marketplace'?'ThÃªm dá»‹ch vá»¥':'Táº¡o tÃ i nguyÃªn'}</button></div></div>
 <div className={`mode-banner ${demo?'demo':''}`}><div><span className="mode-icon">{demo?<Layers3 size={17}/>:<ShieldCheck size={17}/>}</span><span><strong>{demo?'Báº¡n Ä‘ang xem dá»¯ liá»‡u máº«u.':'Workspace riÃªng tÆ° cá»§a báº¡n.'}</strong> {demo?'CÃ¡c tráº¡ng thÃ¡i vÃ  háº¡n má»©c chá»‰ Ä‘á»ƒ minh há»a.':'Káº¿t ná»‘i Meta Ä‘á»ƒ báº¯t Ä‘áº§u, hoáº·c khÃ¡m phÃ¡ giao diá»‡n vá»›i dá»¯ liá»‡u máº«u.'}</span></div><button onClick={()=>setDemo(!demo)}>{demo?'Vá» workspace':'Xem dá»¯ liá»‡u máº«u'}<ArrowRight size={15}/></button></div>
 {error&&<div className="error-banner" role="alert">{error}<button onClick={()=>void load()}>Thá»­ láº¡i</button></div>}
 {(view==='Tá»•ng quan'||nav.find(n=>n.name===view)?.type)&&<>
 <section className="stats-grid" aria-label="Tá»•ng há»£p tÃ i nguyÃªn">{types.map((t,i)=>{const Icon=iconMap[t as keyof typeof iconMap],count=display.filter(a=>a.type===t).length;return <button key={t} className="stat-card" onClick={()=>{setTab(t);if(view!=='Tá»•ng quan')go(nav.find(n=>n.type===t)!.name);}}><div className="stat-top"><span>{['Business Manager','TÃ i khoáº£n quáº£ng cÃ¡o','Facebook Page','Dataset / Pixel'][i]}</span><span className={`stat-icon tone-${i}`}><Icon size={19}/></span></div><div className="stat-value">{loading&&!demo?'â€”':count.toString().padStart(2,'0')}<ArrowUpRight size={19}/></div><div className="stat-bottom"><span className="dot"/><span>{display.filter(a=>a.type===t&&good(a.status)).length} Ä‘ang hoáº¡t Ä‘á»™ng</span><span className="muted">/ {count} tÃ i nguyÃªn</span></div></button>;})}</section>
 {view==='Tá»•ng quan'&&<section className="overview-grid"><div className="panel health-overview"><div className="panel-heading"><h2>Sá»©c khá»e tÃ i nguyÃªn</h2><button className="text-button" onClick={()=>go('Health Check')}>Xem chi tiáº¿t<ArrowUpRight size={15}/></button></div><div className="health-content"><div className="donut" style={{background:display.length?`conic-gradient(#7353e8 0 ${display.filter(a=>good(a.status)).length/display.length*100}%, #efb846 0 ${(display.length-display.filter(a=>a.status==='DIE').length)/display.length*100}%, #ef6c79 0 100%)`:'#eeeef3'}}><div><strong>{display.length?Math.round(display.filter(a=>good(a.status)).length/display.length*100):0}<span>%</span></strong><small>Hoáº¡t Ä‘á»™ng tá»‘t</small></div></div><div className="health-legend">{[['Äang hoáº¡t Ä‘á»™ng',display.filter(a=>good(a.status)).length,'purple'],['Cáº§n kiá»ƒm tra',display.filter(a=>!good(a.status)&&a.status!=='DIE').length,'yellow'],['VÃ´ hiá»‡u hÃ³a',display.filter(a=>a.status==='DIE').length,'pink']].map(([label,count,color])=><div key={label}><span className={`legend-dot ${color}`}/><span>{label}</span><strong>{count}</strong></div>)}<div className="legend-total"><span>Tá»•ng tÃ i nguyÃªn</span><strong>{display.length}</strong></div></div></div></div><div className="panel quick-panel"><div className="panel-heading"><h2>Thao tÃ¡c nhanh</h2><Zap size={17} className="muted"/></div><div className="quick-actions">{[{icon:Plus,title:'Táº¡o hÃ ng loáº¡t',desc:'Cáº¥u hÃ¬nh sá»‘ lÆ°á»£ng & tá»‘c Ä‘á»™',action:()=>open('create')},{icon:Share2,title:'Chia sáº» Ä‘á»‘i tÃ¡c',desc:'Cáº¥p quyá»n tÃ i khoáº£n quáº£ng cÃ¡o',action:()=>open('share')},{icon:Users,title:'Quáº£n lÃ½ quyá»n',desc:'ThÃ nh viÃªn, tÃ i sáº£n & Ä‘á»‘i tÃ¡c',action:()=>open('member')},{icon:HeartPulse,title:'Kiá»ƒm tra tÃ i nguyÃªn',desc:'Tráº¡ng thÃ¡i & quyá»n truy cáº­p',action:()=>go('Health Check')}].map(x=><button key={x.title} onClick={x.action}><span className="quick-icon"><x.icon size={19}/></span><span><strong>{x.title}</strong><small>{x.desc}</small></span><ChevronRight size={16}/></button>)}</div></div></section>}
 </>}
 {(view==='Tá»•ng quan'||view==='Health Check'||nav.find(n=>n.name===view)?.type)&&<section className="panel resources-panel">
 <div className="panel-heading"><div className="inline"><h2>{view==='Health Check'?'Káº¿t quáº£ kiá»ƒm tra':'TÃ i nguyÃªn cá»§a báº¡n'}</h2><span className="count-pill">{view==='Health Check'?display.length:display.filter(a=>a.type===currentType).length}</span></div><div className="inline"><button className="text-button" onClick={exportData}><Download size={15}/>Xuáº¥t CSV</button><button className="button compact" onClick={()=>{setDetail(null);open('asset');}}><Plus size={15}/>ThÃªm há»“ sÆ¡</button></div></div>
 {view==='Tá»•ng quan'&&<div className="resource-tabs">{types.map(t=><button className={tab===t?'selected':''} key={t} onClick={()=>setTab(t)}>{t==='BM'?'Business Manager':t==='TKQC'?'TÃ i khoáº£n quáº£ng cÃ¡o':t}<span>{display.filter(a=>a.type===t).length}</span></button>)}</div>}
 {view==='Health Check'&&<div className="health-notice"><AlertTriangle size={18}/><span>{unhealthy.length} tÃ i nguyÃªn cáº§n chÃº Ã½. Lá»—i truy cáº­p Ä‘Æ°á»£c ghi lÃ  â€œKhÃ´ng xÃ¡c Ä‘á»‹nhâ€, khÃ´ng tá»± káº¿t luáº­n DIE.</span><button className="button compact" disabled={busy||empty} onClick={()=>void act('health',{ids:selected})}><RefreshCw size={14}/>Kiá»ƒm tra {selected.length?'Ä‘Ã£ chá»n':'táº¥t cáº£'}</button></div>}
 <div className="filters"><label className="search-input"><Search size={17}/><input placeholder="TÃ¬m theo tÃªn hoáº·c ID tÃ i nguyÃªn..." aria-label="TÃ¬m tÃ i nguyÃªn" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button className="icon-button" onClick={()=>setQuery('')} aria-label="XÃ³a tÃ¬m kiáº¿m"><X size={14}/></button>}</label><select aria-label="Lá»c tráº¡ng thÃ¡i" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Táº¥t cáº£ tráº¡ng thÃ¡i</option>{Array.from(new Set(display.map(a=>a.status))).map(s=><option key={s}>{s}</option>)}</select><select aria-label="Lá»c quá»‘c gia" value={country} onChange={e=>setCountry(e.target.value)}><option value="all">Quá»‘c gia</option><option>VN</option><option>US</option><option>ChÆ°a rÃµ</option></select><button className={`button ${advanced?'tinted':''}`} onClick={()=>setAdvanced(!advanced)}><SlidersHorizontal size={16}/>Bá»™ lá»c</button></div>
 {advanced&&<div className="advanced-filters"><label>XÃ¡c minh<select value={verified} onChange={e=>setVerified(e.target.value)}><option value="all">Táº¥t cáº£</option><option value="yes">ÄÃ£ xÃ¡c minh</option><option value="no">ChÆ°a xÃ¡c minh</option></select></label><label>PhÃ¢n loáº¡i<select value={tier} onChange={e=>setTier(e.target.value)}><option value="all">Táº¥t cáº£ BM</option>{['BM0','BM3','BM5','BM10','BM25','BM50','ChÆ°a rÃµ'].map(t=><option key={t}>{t}</option>)}</select></label><button className="text-button" onClick={()=>{setVerified('all');setTier('all');setCountry('all');setStatus('all');setQuery('');}}>XÃ³a bá»™ lá»c</button></div>}
 {selected.length>0&&<div className="selection-bar"><strong>ÄÃ£ chá»n {selected.length}</strong><button onClick={()=>void act('health',{ids:selected})} disabled={busy}>Kiá»ƒm tra</button><button onClick={()=>open('share')}>Chia sáº» Ä‘á»‘i tÃ¡c</button><button onClick={()=>open('delete')}>XÃ³a há»“ sÆ¡</button><button onClick={()=>setSelected([])}>Bá» chá»n</button></div>}
 <div className="table-scroll"><table><thead><tr><th><input type="checkbox" aria-label="Chá»n trang hiá»‡n táº¡i" checked={pageRows.length>0&&pageRows.every(a=>selected.includes(a.id))} onChange={e=>setSelected(e.target.checked?Array.from(new Set([...selected,...pageRows.map(a=>a.id)])):selected.filter(id=>!pageRows.some(a=>a.id===id)))}/></th><th>TÃªn {currentType==='BM'?'Business Manager':'tÃ i nguyÃªn'}</th><th>Tráº¡ng thÃ¡i</th><th>XÃ¡c minh</th><th>Quá»‘c gia <small>â“˜</small></th><th>PhÃ¢n loáº¡i</th><th>{view==='Health Check'?'Láº§n kiá»ƒm tra':'Háº¡n má»©c'}</th><th/></tr></thead><tbody>{pageRows.map(a=><tr key={a.id} className={selected.includes(a.id)?'row-selected':''}><td><input type="checkbox" aria-label={`Chá»n ${a.name}`} checked={selected.includes(a.id)} onChange={e=>setSelected(e.target.checked?[...selected,a.id]:selected.filter(id=>id!==a.id))}/></td><td><button className="asset-name" onClick={()=>{setDetail(a);open('detail');}}><span className="asset-avatar">{a.name.split(' ').slice(0,2).map(s=>s[0]).join('')}</span><span><strong>{a.name}</strong><small>{a.source==='demo'?'Dá»® LIá»†U MáºªU':a.source==='manual'?'THá»¦ CÃ”NG':a.id.split('meta:')[1]} Â· {a.type}</small></span></button></td><td><Badge status={a.status}/></td><td>{a.type==='BM'?<span className={`verification ${a.verified?'verified':''}`}>{a.verified?<ShieldCheck size={15}/>:<Clock3 size={14}/>} {a.verified?'ÄÃ£ xÃ¡c minh':'ChÆ°a xÃ¡c minh'}</span>:<span className="muted">â€”</span>}</td><td><span className="country">{a.country==='VN'?'ðŸ‡»ðŸ‡³':a.country==='US'?'ðŸ‡ºðŸ‡¸':'ðŸŒ'} {a.country}</span></td><td><span className="tier">{a.type==='BM'?a.tier:'â€”'}</span></td><td className="limit">{view==='Health Check'?date(a.checked):a.limit}</td><td><button className="icon-button" aria-label={`Chi tiáº¿t ${a.name}`} onClick={()=>{setDetail(a);open('detail');}}><MoreHorizontal size={19}/></button></td></tr>)}</tbody></table></div>
 {rows.length===0&&<div className="empty-state"><div className="empty-icon"><Building2 size={28}/></div><h3>{loading?'Äang táº£i workspaceâ€¦':empty?'Workspace Ä‘Ã£ sáºµn sÃ ng':'KhÃ´ng tÃ¬m tháº¥y tÃ i nguyÃªn'}</h3><p>{empty?'Káº¿t ná»‘i Meta hoáº·c thÃªm há»“ sÆ¡ Ä‘á»ƒ báº¯t Ä‘áº§u quáº£n lÃ½.':'Thá»­ tÃ¬m theo tÃªn khÃ¡c hoáº·c Ä‘iá»u chá»‰nh bá»™ lá»c.'}</p>{empty&&<div className="inline"><button className="button primary" onClick={()=>open('settings')}><Link2 size={15}/>Káº¿t ná»‘i Meta</button><button className="button" onClick={()=>setDemo(true)}>KhÃ¡m phÃ¡ dá»¯ liá»‡u máº«u</button></div>}</div>}
 <div className="table-footer"><span>{rows.length?`${(page-1)*8+1}â€“${Math.min(page*8,rows.length)}`:'0'} trÃªn {rows.length} tÃ i nguyÃªn<span className="footer-note"> Â· Quá»‘c gia vÃ  BM0/3/5 lÃ  nhÃ£n quáº£n lÃ½</span></span><div className="pagination"><button disabled={page===1} onClick={()=>setPage(page-1)} aria-label="Trang trÆ°á»›c">â€¹</button><span>{page}</span><button disabled={page*8>=rows.length} onClick={()=>setPage(page+1)} aria-label="Trang sau">â€º</button></div></div>
 </section>}
 {view==='Tá»± Ä‘á»™ng hÃ³a'&&<><div className="workflow-intro"><div className="flow-step"><Building2/><strong>01. Táº¡o tÃ i nguyÃªn</strong><span>Loáº¡i, tÃªn & sá»‘ lÆ°á»£ng</span></div><ArrowRight/><div className="flow-step"><SlidersHorizontal/><strong>02. Äiá»u phá»‘i</strong><span>Tá»‘c Ä‘á»™ & thá»© tá»± xá»­ lÃ½</span></div><ArrowRight/><div className="flow-step"><Users/><strong>03. Cáº¥p quyá»n</strong><span>Email admin & Ä‘á»‘i tÃ¡c</span></div><ArrowRight/><div className="flow-step"><ScrollText/><strong>04. Theo dÃµi</strong><span>Káº¿t quáº£ & nháº­t kÃ½</span></div></div><div className="panel"><div className="panel-heading"><h2>Workflow Ä‘Ã£ lÆ°u <span className="count-pill">{jobs.length}</span></h2><button className="button primary" onClick={()=>open('create')}><Plus size={16}/>Táº¡o workflow</button></div>{!jobs.length?<div className="empty-state"><Zap size={32}/><h3>Táº¡o workflow Ä‘áº§u tiÃªn</h3><p>Cáº¥u hÃ¬nh má»™t láº§n, lÆ°u láº¡i sá»‘ lÆ°á»£ng, khoáº£ng nghá»‰ vÃ  quyá»n cáº§n cáº¥p.</p><button className="button" onClick={()=>open('create')}>Thiáº¿t láº­p workflow</button></div>:jobs.map(j=><div className="job-row" key={j.id}><span className="job-icon"><Zap size={20}/></span><div><strong>{j.name}</strong><small>{String(j.count)} tÃ i nguyÃªn Â· {String(j.interval)} giÃ¢y / thao tÃ¡c Â· {date(j.created)}</small><p>{String(j.reason)}</p></div><Badge status={j.status}/>{j.status!=='ÄÃ£ há»§y'&&<button className="button compact" disabled={busy} onClick={()=>void act('cancel',{id:j.id})}><X size={14}/>Há»§y</button>}</div>)}</div></>}
 {view==='Nháº­t kÃ½ hoáº¡t Ä‘á»™ng'&&<div className="panel"><div className="panel-heading"><h2>Lá»‹ch sá»­ thao tÃ¡c</h2><span className="count-pill">{logs.length}</span></div>{logs.length?logs.map(l=><div className="log-row" key={l.id}><span className="log-icon"><Check size={17}/></span><div><strong>{l.name}</strong><small>{date(l.created)}</small></div><Badge status={l.status}/></div>):<div className="empty-state"><ScrollText size={32}/><h3>ChÆ°a cÃ³ hoáº¡t Ä‘á»™ng</h3><p>CÃ¡c thao tÃ¡c Ä‘Æ°á»£c lÆ°u thÃ nh cÃ´ng sáº½ xuáº¥t hiá»‡n á»Ÿ Ä‘Ã¢y.</p></div>}</div>}
 {view==='Marketplace'&&<><div className="market-banner"><Store size={34}/><div><h2>Dá»‹ch vá»¥ cho há»‡ thá»‘ng quáº£ng cÃ¡o cá»§a báº¡n</h2><p>LÆ°u nhÃ  cung cáº¥p, thÃ´ng tin dá»‹ch vá»¥ vÃ  Ä‘Æ°á»ng dáº«n liÃªn há»‡. ChÆ°a tÃ­ch há»£p thanh toÃ¡n.</p></div></div><div className="services-grid">{services.map(s=><article className="panel service-card" key={s.id}><span className="service-icon"><Store size={24}/></span><span className="tier">{String(s.category||'Dá»‹ch vá»¥')}</span><h2>{s.name}</h2><p>{String(s.description||'ChÆ°a cÃ³ mÃ´ táº£')}</p><div className="service-provider">{String(s.provider)}<Badge status={s.status}/></div><div className="service-bottom"><strong>{String(s.price||'LiÃªn há»‡')}</strong>{!!s.url&&<a className="text-button" href={String(s.url)} target="_blank" rel="noopener noreferrer">NhÃ  cung cáº¥p<ArrowUpRight size={15}/></a>}</div></article>)}</div>{!services.length&&<div className="panel empty-state"><Store size={32}/><h3>Danh má»¥c nhÃ  cung cáº¥p cÃ²n trá»‘ng</h3><p>ThÃªm dá»‹ch vá»¥ Ä‘á»ƒ quáº£n lÃ½ vÃ  tham kháº£o trong workspace.</p><button className="button primary" onClick={()=>open('service')}><Plus size={16}/>ThÃªm dá»‹ch vá»¥</button></div>}</>}
 {view==='CÃ i Ä‘áº·t'&&<div className="settings-grid"><section className="panel settings-card"><span className="meta-symbol">âˆž</span><h2>Káº¿t ná»‘i Meta</h2><Badge status={connected?'ÄÃ£ cáº¥u hÃ¬nh':'ChÆ°a káº¿t ná»‘i'}/><p>Äá»“ng bá»™ Business Manager, TKQC, Page vÃ  Pixel Ä‘Æ°á»£c cáº¥p quyá»n. Token chá»‰ Ä‘Æ°á»£c sá»­ dá»¥ng á»Ÿ mÃ¡y chá»§.</p><button className="button primary" onClick={()=>open('settings')}>HÆ°á»›ng dáº«n thiáº¿t láº­p<ArrowUpRight size={16}/></button></section><section className="panel settings-card"><Layers3 size={30}/><h2>Dá»¯ liá»‡u workspace</h2><p>Dá»¯ liá»‡u Ä‘Æ°á»£c lÆ°u trong cÆ¡ sá»Ÿ dá»¯ liá»‡u riÃªng tÆ°. Dá»¯ liá»‡u máº«u luÃ´n cÃ³ nhÃ£n vÃ  khÃ´ng Ä‘áº¡i diá»‡n cho tÃ i nguyÃªn tháº­t.</p><div className="inline"><button className="button" onClick={()=>setDemo(!demo)}>{demo?'Vá» workspace':'Xem dá»¯ liá»‡u máº«u'}</button><button className="button" disabled={busy} onClick={async()=>{if(await act('seed'))setDemo(false);}}>Náº¡p bá»™ máº«u vÃ o workspace</button></div></section><section className="panel settings-card wide"><ShieldCheck size={26}/><h2>Tráº¡ng thÃ¡i vÃ  háº¡n má»©c</h2><p>LIVE/DIE Ã¡p dá»¥ng theo tráº¡ng thÃ¡i tÃ i khoáº£n quáº£ng cÃ¡o khi Meta tráº£ vá» dá»¯ liá»‡u. BM vÃ  Page hiá»ƒn thá»‹ â€œTruy cáº­p Ä‘Æ°á»£câ€ khi Ä‘á»c thÃ nh cÃ´ng. Quá»‘c gia lÃ  nhÃ£n quáº£n lÃ½, khÃ´ng pháº£i IP do Meta cung cáº¥p. BM0/BM3/BM5â€¦ lÃ  phÃ¢n loáº¡i ná»™i bá»™. Háº¡n má»©c chÆ°a Ä‘Æ°á»£c xÃ¡c nháº­n sáº½ hiá»ƒn thá»‹ â€œChÆ°a rÃµâ€.</p></section></div>}
 <footer className="page-footer"><span><span className="footer-brand">adsworkspace</span> Â· KhÃ´ng gian quáº£n lÃ½ Meta Ads</span><span>{demo?'Cháº¿ Ä‘á»™ dá»¯ liá»‡u máº«u':'Dá»¯ liá»‡u riÃªng tÆ°'}<span className="footer-separator">/</span><button onClick={()=>open('help')}>Trá»£ giÃºp & hÆ°á»›ng dáº«n <ArrowUpRight size={13}/></button></span></footer>
 </main></div>
 <dialog ref={dialogRef} onCancel={()=>setModal('')} onClick={e=>{if(e.target===dialogRef.current)setModal('');}}><div className="modal-shell"><div className="modal-heading"><div><div className="eyebrow">ADS WORKSPACE</div><h2>{({create:'Táº¡o workflow tÃ i nguyÃªn',asset:'ThÃªm há»“ sÆ¡ tÃ i nguyÃªn',edit:'Chá»‰nh sá»­a há»“ sÆ¡',share:'Chia sáº» vá»›i Ä‘á»‘i tÃ¡c',member:'Quáº£n lÃ½ quyá»n & káº¿t ná»‘i',detail:detail?.name,settings:'Thiáº¿t láº­p káº¿t ná»‘i Meta',help:'HÆ°á»›ng dáº«n workspace',delete:'XÃ³a há»“ sÆ¡ Ä‘Ã£ chá»n',service:'ThÃªm dá»‹ch vá»¥'})[modal]}</h2></div><button className="icon-button" aria-label="ÄÃ³ng" onClick={()=>setModal('')}><X size={21}/></button></div>
 {['create','asset','edit','share','member','service'].includes(modal)&&<form onSubmit={submit} key={modal}>
 {modal==='create'&&<><div className="form-note"><Clock3 size={18}/><span>Workflow Ä‘Æ°á»£c lÆ°u á»Ÿ tráº¡ng thÃ¡i chá». ChÆ°a táº¡o tÃ i nguyÃªn hoáº·c gá»­i lá»i má»i trÃªn Meta.</span></div><label>Loáº¡i tÃ i nguyÃªn<select value={formType} onChange={e=>setFormType(e.target.value)}>{types.map(t=><option key={t}>{t}</option>)}</select></label><label>TÃªn / tiá»n tá»‘ tÃ i nguyÃªn<input name="name" placeholder="VD: Nguyen Media" maxLength={100} required/></label><div className="form-grid"><label>Sá»‘ lÆ°á»£ng<input type="number" min={1} max={100} value={quantity} onChange={e=>setQuantity(Number(e.target.value))} required/></label><label>Khoáº£ng nghá»‰ (giÃ¢y)<input type="number" min={5} max={3600} value={interval} onChange={e=>setIntervalValue(Number(e.target.value))} required/></label></div><label className="range-label">Tá»‘c Ä‘á»™ dá»± kiáº¿n <strong>{Math.round(3600/interval)} thao tÃ¡c / giá»</strong><input type="range" min={5} max={120} step={5} value={Math.min(interval,120)} onChange={e=>setIntervalValue(Number(e.target.value))}/></label>{formType!=='BM'&&<label>BM sá»Ÿ há»¯u<select name="parent" required><option value="">Chá»n BM</option>{bms.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>}<div className="form-divider"/><label>Email quáº£n trá»‹ viÃªn sau khi táº¡o <small>(tÃ¹y chá»n)</small><input name="email" type="email" placeholder="admin@gmail.com"/></label><label>Quyá»n má»i<select name="role"><option value="EMPLOYEE">NhÃ¢n viÃªn</option><option value="ADMIN">Quáº£n trá»‹ viÃªn</option></select></label><p className="field-help">Nháº­p Ä‘á»‹a chá»‰ email ngÆ°á»i nháº­n. Link Gmail khÃ´ng pháº£i lá»i má»i quáº£n trá»‹ Meta. NgÆ°á»i nháº­n váº«n cáº§n cháº¥p nháº­n lá»i má»i.</p><div className="workflow-summary"><Clock3 size={17}/><span>{quantity} tÃ i nguyÃªn Â· tá»‘i thiá»ƒu {Math.max(0,(quantity-1)*interval)} giÃ¢y khoáº£ng nghá»‰</span></div></>}
 {(modal==='asset'||modal==='edit')&&<><p className="field-help">LÆ°u há»“ sÆ¡ Ä‘á»ƒ theo dÃµi; thao tÃ¡c nÃ y khÃ´ng táº¡o tÃ i nguyÃªn trÃªn Meta.</p><label>TÃªn<input name="name" required maxLength={150} defaultValue={modal==='edit'?detail?.name:''}/></label><label>Loáº¡i<select value={formType} onChange={e=>setFormType(e.target.value)} disabled={modal==='edit'}>{types.map(t=><option key={t}>{t}</option>)}</select></label><div className="form-grid"><label>Quá»‘c gia (nhÃ£n)<select name="country" defaultValue={detail?.country||'VN'}><option>VN</option><option>US</option><option>ChÆ°a rÃµ</option></select></label><label>PhÃ¢n loáº¡i (nhÃ£n)<select name="tier" defaultValue={detail?.tier||'ChÆ°a rÃµ'}>{['ChÆ°a rÃµ','BM0','BM3','BM5','BM10','BM25','BM50'].map(t=><option key={t}>{t}</option>)}</select></label></div><label>Háº¡n má»©c ghi chÃº<input name="limit" defaultValue={detail?.limit||'ChÆ°a rÃµ'} readOnly={detail?.source==='meta'}/></label>{formType!=='BM'&&<label>BM liÃªn káº¿t<select name="parent"><option value="">ChÆ°a liÃªn káº¿t</option>{bms.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>}</>}
 {modal==='share'&&<><div className="form-note"><Share2 size={18}/><span>LÆ°u yÃªu cáº§u cáº¥p quyá»n qua luá»“ng Ä‘á»‘i tÃ¡c cho TKQC Ä‘ang hoáº¡t Ä‘á»™ng.</span></div><label>Chá»n Business Manager<select value={shareBm} onChange={e=>{setShareBm(e.target.value);setShareIds([]);}} required><option value="">Chá»n BM</option>{bms.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>ID Business cá»§a Ä‘á»‘i tÃ¡c<input name="partner" inputMode="numeric" pattern="[0-9]{5,30}" required placeholder="VD: 123456789012345"/></label><label>Quyá»n tÃ i khoáº£n quáº£ng cÃ¡o<select name="role"><option value="ANALYZE">Xem hiá»‡u quáº£</option><option value="ADVERTISE">Quáº£n lÃ½ chiáº¿n dá»‹ch</option><option value="MANAGE">Quáº£n lÃ½ tÃ i khoáº£n</option></select></label><div className="segmented"><button type="button" className={!random?'selected':''} onClick={()=>setRandom(false)}>Chá»n tÃ i khoáº£n</button><button type="button" className={random?'selected':''} onClick={()=>setRandom(true)}>Chá»n ngáº«u nhiÃªn</button></div>{random?<label>Sá»‘ lÆ°á»£ng ngáº«u nhiÃªn<input type="number" value={quantity} min={1} max={Math.max(1,eligible.length)} onChange={e=>setQuantity(Number(e.target.value))}/><small>{eligible.length} TKQC Ä‘á»§ Ä‘iá»u kiá»‡n trong BM</small></label>:<div className="account-options">{eligible.length?eligible.map(a=><label className="check-label" key={a.id}><input type="checkbox" checked={shareIds.includes(a.id)} onChange={e=>setShareIds(e.target.checked?[...shareIds,a.id]:shareIds.filter(id=>id!==a.id))}/><span>{a.name}</span><Badge status={a.status}/></label>):<p>BM nÃ y chÆ°a cÃ³ TKQC Ä‘ang hoáº¡t Ä‘á»™ng.</p>}</div>}<p className="field-help">Danh sÃ¡ch tÃ i khoáº£n cá»¥ thá»ƒ Ä‘Æ°á»£c lÆ°u cÃ¹ng workflow Ä‘á»ƒ báº¡n kiá»ƒm tra trÆ°á»›c khi thá»±c thi.</p></>}
 {modal==='member'&&<><label>Thao tÃ¡c<select value={operation} onChange={e=>setOperation(e.target.value)}><option value="member">Má»i thÃ nh viÃªn</option><option value="remove-member">Gá»¡ thÃ nh viÃªn</option><option value="remove-partner">Gá»¡ Ä‘á»‘i tÃ¡c</option><option value="connect">Káº¿t ná»‘i tÃ i nguyÃªn</option><option value="detach">Gá»¡ liÃªn káº¿t tÃ i nguyÃªn</option></select></label><label>Business Manager<select name="parent" required><option value="">Chá»n BM</option>{bms.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select></label>{operation==='member'?<label>Email thÃ nh viÃªn<input name="email" type="email" required placeholder="name@gmail.com"/></label>:<label>ID {operation.includes('member')?'thÃ nh viÃªn':operation.includes('partner')?'Ä‘á»‘i tÃ¡c':'tÃ i nguyÃªn'}<input name="targetId" required pattern="[0-9]{5,30}"/></label>}<label>Quyá»n<select name="role"><option value="EMPLOYEE">NhÃ¢n viÃªn / quyá»n cÆ¡ báº£n</option><option value="ADMIN">Quáº£n trá»‹ viÃªn</option></select></label><div className="form-note">Cáº¥u hÃ¬nh Ä‘Æ°á»£c lÆ°u Ä‘á»ƒ rÃ  soÃ¡t. ChÆ°a thay Ä‘á»•i thÃ nh viÃªn, Ä‘á»‘i tÃ¡c hoáº·c tÃ i sáº£n trÃªn Meta.</div></>}
 {modal==='service'&&<><label>TÃªn dá»‹ch vá»¥<input name="name" maxLength={150} required placeholder="VD: Thiáº¿t láº­p Pixel & Conversions API"/></label><label>NhÃ  cung cáº¥p<input name="provider" maxLength={150} required/></label><label>Danh má»¥c<select name="category"><option>Thiáº¿t láº­p & tÃ­ch há»£p</option><option>Quáº£n lÃ½ quáº£ng cÃ¡o</option><option>Thiáº¿t káº¿ & ná»™i dung</option><option>TÆ° váº¥n & há»— trá»£</option><option>TÃ i nguyÃªn Ä‘Æ°á»£c phÃ©p chuyá»ƒn giao</option></select></label><label>MÃ´ táº£<textarea name="description" rows={3}/></label><div className="form-grid"><label>GiÃ¡ tham kháº£o<input name="price" placeholder="LiÃªn há»‡"/></label><label>Website nhÃ  cung cáº¥p<input name="url" type="url" placeholder="https://..."/></label></div></>}
 {formError&&<p className="form-error" role="alert">{formError}</p>}<div className="modal-footer"><button type="button" className="button" onClick={()=>setModal('')}>Há»§y</button><button className="button primary" disabled={busy||demo} type="submit">{busy?'Äang lÆ°uâ€¦':modal==='create'||modal==='share'||modal==='member'?'LÆ°u cáº¥u hÃ¬nh workflow':'LÆ°u thÃ´ng tin'}<ArrowRight size={16}/></button></div>{demo&&<p className="field-help">Chuyá»ƒn vá» workspace Ä‘á»ƒ lÆ°u thay Ä‘á»•i.</p>}</form>}
 {modal==='detail'&&detail&&<><div className="detail-top"><span className="asset-avatar large">{detail.name[0]}</span><div><Badge status={detail.status}/><p>{detail.source==='demo'?'Dá»¯ liá»‡u máº«u':detail.source==='meta'?'Äá»“ng bá»™ tá»« Meta':'Há»“ sÆ¡ thá»§ cÃ´ng'}</p></div></div><dl className="detail-grid">{[['Loáº¡i',detail.type],['ID',detail.id],['Quá»‘c gia (nhÃ£n)',detail.country],['PhÃ¢n loáº¡i (nhÃ£n)',detail.tier],['Háº¡n má»©c',detail.limit],['XÃ¡c minh',detail.verified?'ÄÃ£ xÃ¡c minh':'ChÆ°a xÃ¡c minh'],['Láº§n kiá»ƒm tra',date(detail.checked)],['BM sá»Ÿ há»¯u',display.find(a=>a.id===detail.parent)?.name||'â€”'],['Káº¿t quáº£ kiá»ƒm tra',detail.healthNote||'ChÆ°a cÃ³ káº¿t quáº£ má»›i']].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><div className="modal-footer"><button className="button" onClick={()=>{setFormType(detail.type);setModal('edit');}}>Sá»­a há»“ sÆ¡</button><button className="button primary" disabled={busy} onClick={()=>void act('health',{ids:[detail.id]})}><HeartPulse size={16}/>Kiá»ƒm tra</button></div></>}
 {modal==='settings'&&<div className="setup-content"><span className="meta-symbol">âˆž</span><p>Káº¿t ná»‘i phÃ­a mÃ¡y chá»§ báº£o vá»‡ token, khÃ´ng lÆ°u token trong trÃ¬nh duyá»‡t.</p><ol><li><strong>Chuáº©n bá»‹ Meta App</strong><p>á»¨ng dá»¥ng vÃ  tÃ i khoáº£n Ä‘Æ°á»£c Meta cáº¥p quyá»n quáº£n lÃ½ tÃ i nguyÃªn cá»§a báº¡n.</p></li><li><strong>Cáº¥u hÃ¬nh káº¿t ná»‘i mÃ¡y chá»§</strong><p>Thiáº¿t láº­p secret <code>META_ACCESS_TOKEN</code> vÃ  <code>META_API_VERSION</code> trong mÃ´i trÆ°á»ng triá»ƒn khai. KhÃ´ng gá»­i token vÃ o chat.</p></li><li><strong>Kiá»ƒm tra quyá»n truy cáº­p</strong><p>Quyá»n cáº§n thiáº¿t phá»¥ thuá»™c tÃ i nguyÃªn vÃ  thao tÃ¡c, bao gá»“m business_management vÃ  cÃ¡c quyá»n quáº£ng cÃ¡o / Page tÆ°Æ¡ng á»©ng.</p></li><li><strong>Äá»“ng bá»™ tÃ i nguyÃªn</strong><p>á»¨ng dá»¥ng Ä‘á»c BM, tÃ i khoáº£n quáº£ng cÃ¡o, Page vÃ  Pixel Ä‘Æ°á»£c phÃ©p truy cáº­p. Táº¡o vÃ  phÃ¢n quyá»n Ä‘ang á»Ÿ bÆ°á»›c lÆ°u cáº¥u hÃ¬nh, chÆ°a cÃ³ bá»™ thá»±c thi.</p></li></ol><a className="text-button" href="https://developers.facebook.com/docs/marketing-api/business-manager-api/" target="_blank" rel="noopener noreferrer">TÃ i liá»‡u chÃ­nh thá»©c Meta<ExternalLink size={14}/></a><div className="modal-footer"><button className="button" onClick={()=>setModal('')}>ÄÃ³ng</button><button className="button primary" disabled={!connected||busy} onClick={async()=>{if(await act('sync'))setModal('');}}><RefreshCw size={16}/>Äá»“ng bá»™ ngay</button></div></div>}
 {modal==='help'&&<div className="setup-content"><p><strong>1. Káº¿t ná»‘i hoáº·c thÃªm há»“ sÆ¡.</strong> Káº¿t ná»‘i Meta Ä‘á»ƒ Ä‘á»c dá»¯ liá»‡u thá»±c; há»“ sÆ¡ thá»§ cÃ´ng vÃ  dá»¯ liá»‡u máº«u cÃ³ nhÃ£n riÃªng.</p><p><strong>2. Quáº£n lÃ½ táº­p trung.</strong> TÃ¬m kiáº¿m, lá»c, chá»n nhiá»u tÃ i nguyÃªn vÃ  xuáº¥t CSV. Chá»n tÃªn Ä‘á»ƒ xem chi tiáº¿t.</p><p><strong>3. LÆ°u workflow.</strong> Thiáº¿t láº­p táº¡o hÃ ng loáº¡t, khoáº£ng nghá»‰, email admin hoáº·c chia sáº» TKQC theo ID Ä‘á»‘i tÃ¡c. Workflow chÆ°a Ä‘Æ°á»£c thá»±c thi trÃªn Meta.</p><p><strong>4. Kiá»ƒm tra & theo dÃµi.</strong> Health Check Ä‘á»c tÃ i nguyÃªn Ä‘Ã£ káº¿t ná»‘i; lá»—i quyá»n khÃ´ng Ä‘á»“ng nghÄ©a tÃ i nguyÃªn bá»‹ vÃ´ hiá»‡u hÃ³a.</p><button className="button primary" onClick={()=>setModal('')}>ÄÃ£ hiá»ƒu</button></div>}
 {modal==='delete'&&<><p>XÃ³a {selected.length} há»“ sÆ¡ khá»i workspace. TÃ i nguyÃªn trÃªn Meta váº«n Ä‘Æ°á»£c giá»¯ nguyÃªn.</p><div className="modal-footer"><button className="button" onClick={()=>setModal('')}>Há»§y</button><button className="button danger" disabled={busy} onClick={async()=>{if(await act('delete',{ids:selected})){setSelected([]);setModal('');}}}>XÃ³a {selected.length} há»“ sÆ¡</button></div></>}
 </div></dialog>
 {toast&&<div className="toast" role="status"><CheckCircle2 size={19}/><span>{toast}</span><button className="icon-button" aria-label="ÄÃ³ng thÃ´ng bÃ¡o" onClick={()=>setToast('')}><X size={16}/></button></div>}
 </div>;
}

