export type Asset = {
 id:string;
 name:string;
 type:string;
 status:string;
 verified:boolean;
 country:string;
 tier:string;
 limit:string;
 parent:string;
 source:string;
 checked?:string;
 currency?:string;
 metaStatus?:number;
 accountStatus?:number;
 disableReason?:number;
 amountSpent?:string;
 balance?:string;
 spendCap?:string;
 minDailyBudget?:string;
 billingType?:'PREPAID'|'POSTPAID'|'UNKNOWN';
 hasFundingSource?:boolean;
 fundingType?:string;
 fundingDisplay?:string;
 timezoneName?:string;
 timezoneOffsetHoursUtc?:number;
 ownerId?:string;
 ownership?:'owned'|'client'|'unknown';
 businessName?:string;
 category?:string;
 followersCount?:number;
 fanCount?:number;
 pageLink?:string;
 vertical?:string;
 twoFactorType?:string;
 updatedTime?:string;
 lastFiredTime?:string;
 healthNote?:string;
 metaId?:string;
 verificationStatus?:string;
 creationTime?:string;
 timezoneId?:string;
 primaryPageId?:string;
 primaryPageName?:string;
 createdById?:string;
 createdByName?:string;
 sourceTokenId?:string;
 adAccountCount?:number|null;
 ownedAdAccountCount?:number|null;
 pageCount?:number|null;
 observedAdAccountCount?:number;
 observedOwnedAdAccountCount?:number;
 observedPageCount?:number;
 bmDetailsStatus?:'complete'|'partial'|'unavailable';
 userCount?:number;
 adminEmail?:string;
 adminInviteStatus?:string;
 adminInviteError?:string;
 crmPushStatus?:string;
 crmPushAt?:string;
 crmResourceId?:string;
 crmBatchId?:string;
 bmType?:string;
 accountCapacity?:number|null;
 currencies?:string[];
 currencyMode?:'SINGLE'|'MULTI'|'NONE';
 assetSources?:Array<'graph_accounts'|'session'|'bm_owned'|'bm_client'>;
 openUrl?:string;
 accessLink?:string;
 accessLinkGeneratedAt?:string;
 accessLinkStatus?:'none'|'generating'|'ready'|'failed';
 accessLinkError?:string;
 shopStatus?:'not_ready'|'ready'|'pushing'|'pushed'|'failed';
 shopProductId?:string;
 shopSyncedAt?:string;
 shopError?:string;
 creationStatus?:'created'|'failed';
 checkStatus?:'pending'|'ready'|'failed';
 syncStatus?:'pending'|'ready'|'failed';
 // Model trạng thái TKQC tách ba lớp (xem lib/ad-status.ts). Optional để tương thích
 // với asset cũ trong D1 — payload không có các field này vẫn đọc được.
 accessStatus?:'ACCESSIBLE'|'ACCESS_LOST'|'UNKNOWN';
 deliveryStatus?:'LIVE'|'DISABLED'|'RESTRICTED'|'PENDING'|'UNSETTLED'|'CLOSED'|'UNKNOWN';
 readSource?:'GRAPH'|'SESSION'|'BM_EDGE'|'MIXED'|'UNKNOWN';
 rawAccountStatus?:number;
 checkWarnings?:string[];
 // Freshness tách theo loại dữ liệu thay vì một mốc `checked` duy nhất.
 authCheckedAt?:string;
 resourceScannedAt?:string;
 statusCheckedAt?:string;
};
export type Entry = { id:string; name:string; status:string; created:string; [key:string]:unknown };
export const types = ['BM', 'TKQC', 'Page', 'Dataset/Pixel'];
export const demoAssets:Asset[] = Array.from({length:24},(_,i)=>({
 id:`demo-${i+1}`,name:i<8?['Nguyễn Media','Growth Agency','Ecommerce Việt Nam','US Performance','Saigon Digital','Global Commerce','Creative Studio','D2C Vietnam'][i]:`${i<16?'Ads':i<20?'Page':'Pixel'} · ${['Nguyễn Media','Growth Agency','Ecommerce','US Performance'][i%4]} ${i+1}`,
 type:i<8?'BM':i<16?'TKQC':i<20?'Page':'Dataset/Pixel',status:i===3||i===11?'Hạn chế':i===6?'DIE':'LIVE',verified:i%3!==0,country:i%3===0?'US':'VN',tier:['BM5','BM3','BM10','BM0'][i%4],limit:['250 USD','50 USD','1.500 USD','Chưa rõ'][i%4],parent:i<8?'':`demo-${i%8+1}`,source:'demo',currency:'USD',checked:'2026-09-10T02:30:00.000Z'
}));
