import { env } from 'cloudflare:workers';
import { getChatGPTUser } from '../app/chatgpt-auth';
export function db(){const binding=(env as unknown as {DB:D1Database}).DB;if(!binding)throw new Error('Cơ sở dữ liệu chưa sẵn sàng.');return binding;}
export async function owner(){const user=await getChatGPTUser();if(user)return user.userId;if(process.env.NODE_ENV==='development')return 'local-preview';throw new Error('Vui lòng đăng nhập để tiếp tục.');}
export async function list(user:string,kind:string){const r=await db().prepare('SELECT payload FROM records WHERE owner = ? AND kind = ? ORDER BY created DESC').bind(user,kind).all<{payload:string}>();return r.results.map(r=>JSON.parse(r.payload));}
export function put(user:string,kind:string,value:Record<string,unknown>){return db().prepare('INSERT INTO records (id,owner,kind,payload,created) VALUES (?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload WHERE records.owner=excluded.owner').bind(String(value.id),user,kind,JSON.stringify(value),String(value.created||new Date().toISOString()));}
export function audit(user:string,name:string,status='Hoàn tất'){return put(user,'log',{id:crypto.randomUUID(),name,status,created:new Date().toISOString()});}
export function config(){const e=env as unknown as Record<string,string>;return {token:e.META_ACCESS_TOKEN,version:e.META_API_VERSION||'v26.0'};}
export async function graph(path:string,params:Record<string,string>={}){const c=config();if(!c.token)throw new Error('Chưa kết nối Meta. Cần cấu hình META_ACCESS_TOKEN trên máy chủ.');const url=new URL(`https://graph.facebook.com/${c.version}/${path}`);for(const[k,v]of Object.entries(params))url.searchParams.set(k,v);const response=await fetch(url,{headers:{Authorization:`Bearer ${c.token}`},signal:AbortSignal.timeout(25000)});const body=await response.json() as {error?:{message:string;code:number};data?:Record<string,unknown>[];paging?:{cursors?:{after?:string};next?:string};[key:string]:unknown};if(!response.ok||body.error)throw new Error(body.error?.message||'Meta không trả về dữ liệu hợp lệ.');return body;}
export async function graphList(path:string,fields:string){let after='';const rows:Record<string,unknown>[]=[];for(let page=0;page<50;page++){const result=await graph(path,{fields,limit:'100',...(after?{after}:{})});rows.push(...(result.data||[]));if(!result.paging?.next)return rows;after=result.paging.cursors?.after||'';if(!after)throw new Error('Không đọc được trang tiếp theo của Meta.');}throw new Error('Dữ liệu vượt giới hạn một lần đồng bộ.');}
